### ISSUE TITLE
 Not readable code

### ISSUE THREAD

**Issue by Jarosic** [Arkant/MyArray#23]
https://github.com/Arkant/MyArray/blob/961be2993b536dfe85cb426013e4d75b03b65684/src/index.js#L177

**Comment by motifej** [comment]
@Jarosic  give plz a little bit more explanation(maybe some better options)

**Comment by Jarosic** [comment]
i did it like this 
 const arr = new MyArray();
    let firstIndex = begin ? begin : 0;
    let lastIndex = end ? end : this.length;

    firstIndex = firstIndex < 0 ? this.length + firstIndex : firstIndex;
    lastIndex = lastIndex < 0 ? this.length + lastIndex : lastIndex;

    for (let i = firstIndex; i < lastIndex; i++) {
      arr.push(this[i]);
    }
    return arr;
